
backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"
publish_mode: editorial_workflow

collections:
  - name: "settings"
    label: "Site Settings"
    files:
      - name: "general"
        label: "General Settings"
        file: "src/content/settings.json"
        fields:
          - { label: "Site Title", name: "siteTitle", widget: "string" }
          - { label: "Site Description", name: "siteDescription", widget: "string" }
          
  - name: "nav"
    label: "Navigation"
    file: "src/content/navigation.json"
    fields:
      - label: "Menu Items"
        name: "menuItems"
        widget: "list"
        fields:
          - { label: "Label", name: "label", widget: "string" }
          - { label: "Link", name: "link", widget: "string" }
  
  - name: "hero"
    label: "Hero Section"
    file: "src/content/hero.json"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Headline", name: "headline", widget: "string" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "CTA Primary Text", name: "ctaPrimaryText", widget: "string" }
      - { label: "CTA Primary Link", name: "ctaPrimaryLink", widget: "string" }
      - { label: "CTA Secondary Text", name: "ctaSecondaryText", widget: "string" }
      - { label: "CTA Secondary Link", name: "ctaSecondaryLink", widget: "string" }
      - { label: "Background Image", name: "backgroundImage", widget: "image", required: false }

  - name: "services"
    label: "Services"
    file: "src/content/services.json"
    fields:
      - { label: "Section Title", name: "title", widget: "string" }
      - { label: "Section Subtitle", name: "subtitle", widget: "string" }
      - label: "Service Items"
        name: "serviceItems"
        widget: "list"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Icon", name: "icon", widget: "string", hint: "Icon name from Lucide icons" }

  - name: "about"
    label: "About Section"
    file: "src/content/about.json"
    fields:
      - { label: "Section Title", name: "title", widget: "string" }
      - { label: "Summary", name: "summary", widget: "markdown" }
      - label: "Key Strengths"
        name: "strengths"
        widget: "list"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }

  - name: "skills"
    label: "Skills & Certifications"
    file: "src/content/skills.json"
    fields:
      - { label: "Section Title", name: "title", widget: "string" }
      - { label: "Section Subtitle", name: "subtitle", widget: "string" }
      - label: "Skill Categories"
        name: "categories"
        widget: "list"
        fields:
          - { label: "Category Name", name: "name", widget: "string" }
          - { label: "Skills", name: "skills", widget: "list" }
      - label: "Certifications"
        name: "certifications"
        widget: "list"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Issuer", name: "issuer", widget: "string", required: false }
          - { label: "Year", name: "year", widget: "string", required: false }

  - name: "testimonials"
    label: "Testimonials"
    file: "src/content/testimonials.json"
    fields:
      - { label: "Section Title", name: "title", widget: "string" }
      - { label: "Section Subtitle", name: "subtitle", widget: "string" }
      - label: "Testimonial Items"
        name: "testimonialItems"
        widget: "list"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Title/Role", name: "role", widget: "string" }
          - { label: "Quote", name: "quote", widget: "text" }
          - { label: "Avatar", name: "avatar", widget: "image", required: false }
          - { label: "LinkedIn URL", name: "linkedin", widget: "string", required: false }

  - name: "hobby"
    label: "Hobby Projects"
    file: "src/content/hobby.json"
    fields:
      - { label: "Section Title", name: "title", widget: "string" }
      - { label: "Section Subtitle", name: "subtitle", widget: "string" }
      - label: "Project Items"
        name: "projectItems"
        widget: "list"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Image", name: "image", widget: "image", required: false }
          - { label: "URL", name: "url", widget: "string", required: false }

  - name: "contact"
    label: "Contact Section"
    file: "src/content/contact.json"
    fields:
      - { label: "Section Title", name: "title", widget: "string" }
      - { label: "Section Subtitle", name: "subtitle", widget: "string" }
      - { label: "Email", name: "email", widget: "string" }
      - { label: "Phone", name: "phone", widget: "string" }
      - { label: "LinkedIn", name: "linkedin", widget: "string" }
      - { label: "City", name: "city", widget: "string" }
      - { label: "CTA Text", name: "ctaText", widget: "string" }
      - label: "Languages"
        name: "languages"
        widget: "list"
        fields:
          - { label: "Language", name: "language", widget: "string" }
          - { label: "Level", name: "level", widget: "string" }
